package com.dhcc.pms.ws.ord;

import java.util.List;

import javax.annotation.PostConstruct;
import javax.annotation.Resource;
import javax.jws.WebMethod;
import javax.jws.WebService;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.dhcc.framework.transmission.event.BusinessRequest;
import com.dhcc.pms.blh.ord.OrderStateBlh;
import com.dhcc.pms.dto.ord.OrderStateDto;
import com.dhcc.pms.entity.vo.ord.OrderItmVo;

/**
 * @author auto-generated by AnnoParameterParser
 * @timestamp 2014-06-06 17:29:29.343
 */
@WebService(endpointInterface = "com.dhcc.pms.ws.ord.OrderStateWServiceInterface",targetNamespace="http://ord.ws.pms.dhcc.com",
portName="OrderStateWServiceServiceHttpSoap12Endpoint")
public class OrderStateWService implements OrderStateWServiceInterface{

    private static Log logger = LogFactory.getLog(OrderStateWServiceInterface.class);

    @Resource
    private OrderStateBlh blh;

    @com.dhcc.framework.annotation.Descript("查询订单")
   /**
    * 方法名:                list
    * 方法功能描述：                                          查询订单
    * @param  emflag 是否加急
    * @return com.dhcc.framework.common.PagerModel   术语类型是{@linkplain java.lang.String}  值域类型是{@linkplain java.lang.String}
    * @see java.lang.String
    * @see java.lang.String
    * @since JDK1.7
    * @Create Date:        2014-06-06 17:29:29.343
    */
    @Override
    @WebMethod
    public com.dhcc.framework.common.PagerModel list(java.lang.String emflag) {

        OrderStateDto dto = new OrderStateDto();
        BusinessRequest request = new BusinessRequest();
        request.setDto(dto);

        try {
            blh.list(request);
        } catch(Exception e) {
            logger.error(e.getMessage(), e);
        }
        if(dto.getPageModel() != null) {
            return (com.dhcc.framework.common.PagerModel)dto.getPageModel().getPageData().get(0);
        }
        return null;
    }

    @com.dhcc.framework.annotation.Descript("订单明细")
   /**
    * 方法名:                listOrdItm
    * 方法功能描述：                                          订单明细
    * @param  exeState.ordId 订单ID  pageModel.pageSize 每页条数  pageModel.pageNo 当前页数
    * @return com.dhcc.framework.common.PagerModel   术语类型是{@linkplain int}  值域类型是{@linkplain int}
    * @see int
    * @see int
    * @since JDK1.7
    * @Create Date:        2014-06-06 17:29:29.344
    */
    @Override
    @WebMethod
    public List<OrderItmVo> listOrdItm(int pageNo, int pageSize, java.lang.Long ordId) {

        OrderStateDto dto = new OrderStateDto();
        com.dhcc.framework.common.PagerModel pageModel = new com.dhcc.framework.common.PagerModel();
        pageModel.setPageNo(pageNo);
        pageModel.setPageSize(pageSize);
        com.dhcc.pms.entity.ord.ExeState exeState = new com.dhcc.pms.entity.ord.ExeState();
        exeState.setOrdId(ordId);
        BusinessRequest request = new BusinessRequest();
        request.setDto(dto);

        try {
            blh.listOrdItm(request);
        } catch(Exception e) {
            logger.error(e.getMessage(), e);
        }
            return (List<OrderItmVo>) dto.getPageModel().getPageData();
       
    }

    @PostConstruct
    private void preRegister() {
        com.dhcc.framework.common.WsInfoHolder.registWsInfo(OrderStateWServiceInterface.class);
    }
}